# Generated by Django 3.2.3 on 2021-05-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.checkeditem'),
        ),
    ]
